<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Weeds Information Hub</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      background-color: #f4f4f4;
      color: #333;
    }

    header {
      background: #4CAF50;
      color: white;
      padding: 20px 0;
      text-align: center;
    }

    nav {
      background: #333;
      display: flex;
      justify-content: center;
      gap: 15px;
      padding: 10px;
    }

    nav a {
      color: white;
      text-decoration: none;
      font-weight: bold;
    }

    nav a:hover {
      text-decoration: underline;
    }

    section {
      padding: 20px;
      max-width: 900px;
      margin: auto;
    }

    h2 {
      color: #4CAF50;
    }

    .weed-gallery {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
    }

    .weed-card {
      background: white;
      padding: 15px;
      border-radius: 8px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      flex: 1 1 250px;
    }

    .weed-card img {
      max-width: 100%;
      border-radius: 5px;
    }

    footer {
      text-align: center;
      padding: 15px;
      background: #333;
      color: white;
    }

    @media (max-width: 600px) {
      .weed-gallery {
        flex-direction: column;
      }
    }
  </style>
</head>
<body>

  <header>
    <h1>Weeds Information Hub</h1>
    <p>Your guide to understanding and managing weeds</p>
  </header>

  <nav>
    <a href="#about">About</a>
    <a href="#types">Types of Weeds</a>
    <a href="#contact">Contact</a>
  </nav>

  <section id="about">
    <h2>About Weeds</h2>
    <p>Weeds are unwanted plants that grow in gardens, lawns, or agricultural areas. While often seen as a nuisance, they can also play important ecological roles. Learning to identify and manage weeds is key for maintaining healthy ecosystems and productive farms.</p>
  </section>

  <section id="types">
    <h2>Common Types of Weeds</h2>
    <div class="weed-gallery">
      <div class="weed-card">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Dandelion_lg.jpg/320px-Dandelion_lg.jpg" alt="Dandelion" />
        <h3>Dandelion</h3>
        <p>A common weed with bright yellow flowers and fluffy seed heads. Dandelions are edible and have medicinal uses.</p>
      </div>
      <div class="weed-card">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Crabgrass.jpg/320px-Crabgrass.jpg" alt="Crabgrass" />
        <h3>Crabgrass</h3>
        <p>This fast-spreading weed invades lawns and gardens, competing with grass for sunlight and nutrients.</p>
      </div>
      <div class="weed-card">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Broadleaf_Plantain_Plantago_major.jpg/320px-Broadleaf_Plantain_Plantago_major.jpg" alt="Plantain Weed" />
        <h3>Plantain</h3>
        <p>Broadleaf plantain is a hardy weed found in compacted soil. Its leaves are sometimes used for herbal remedies.</p>
      </div>
    </div>
  </section>

  <section id="contact">
    <h2>Contact Us</h2>
    <p>If you have questions or would like to contribute information or images about weeds, please email us at:</p>
    <p><strong>weedsinfo@example.com</strong></p>
  </section>

  <footer>
    <p>&copy; 2025 Weeds Information Hub. All rights reserved.</p>
  </footer>

</body>
</html>
