<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Computer Hub</title>
</head>
<body>
    <header>
        <h1>Welcome to Computer Hub</h1>
    </header>

    <nav>
        <ul>
            <li><a href="#hardware">Hardware</a></li>
            <li><a href="#software">Software</a></li>
            <li><a href="#news">Tech News</a></li>
        </ul>
    </nav>

    <main>
        <section id="hardware">
            <h2>Computer Hardware</h2>
            <p>Discover the latest innovations in processors, memory, and graphics cards.</p>
        </section>

        <section id="software">
            <h2>Computer Software</h2>
            <p>Explore operating systems, applications, and programming languages.</p>
        </section>

        <section id="news">
            <h2>Tech News</h2>
            <p>Stay updated with the latest trends in computing and technology.</p>
        </section>
    </main>

    <footer>
        <p>&copy; 2025 Computer Hub. All rights reserved.</p>
    </footer>
</body>
</html>
